name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1.1.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for opening you first Issue! Please make sure that you have read the Contribution guidelines and the Code of Conduct."
        pr-message: "Thank you for opening your first Pull-Request! Please make sure that you have read the Contribution guidelines and the Code of Conduct."
